language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls

# safelist
branches:
  only:
    - develop
    - ch-setup-API-development-environment-161814984
    - ft-get-user-orders-API-161716368
    - ft-parcels-get-API-161814924
    - ft-parcels-get-specific-API-161716421
    - ft-parcels-post-API-161814888
    - ft-parcels-put-API-161716449